server:
  port: 9061
spring:
  application:
    name: integral-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.128:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

